language: minimal
sudo: false

git:
  submodules: false

cache:
  directories:
    - $HOME/.mafia

matrix:
  include:
  - env: GHCVER=8.4.4 CABALVER=2.0
    addons:
      apt:
        sources:
          - hvr-ghc
        packages:
          - ghc-8.4.4
          - cabal-install-2.0
  #allow-failures:
  #  - env: GHCVER=head
addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - ghc-7.10.2
      - libgmp-dev

before_install:
  # ghc
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH

script:
  - bin/ci

notifications:
  slack:
    secure: etAFu2hMEGetvR7l+91DHcmSzzzRZloMkQgQLbHyH+q1Z3iSWe4xFyEltOi5vFdvVZokrqO71aUg2c4GhR+0gWHgd5XxsEwk5Ye+bKaJLxKFgwalzJVKiQ1swN3eUZMIBIVIknuMdtIR1pWsPyEdzEz/o2sZxKqi0zhYpCT6Q97LN2Stp+pGxuu2fhOoTCvBn3iU0kqw4wDYfOUqp76gxGgZriUBlN8N/MbwRgaV39gqcEQOGh9TLolIYrpaOCXwLwGCIC8Xc3aJBsL5zQHG9SxQcJiVAer2MLIA2vfYatZGhoNpZ90iUeG3h6y7Lzom6ApDL8XkqR1OLe2YqpQeGD26mDJvYGkXd8ZbopuJYBBr5Jk+EiMbwY5zRr4YwgYsZfsN5rV0d7kbBHodsHnYk5mnPC1OBWh5Z0aLskBmDEOwFsXc1JA/EPBTET/bK3W5OxD/Ptlaw4By+57lTG/4suP+AzGZyHbKnWfeW134OJsJpopPUfZq5Xr3xPOP6pQsKk/P9oPBhRjyWJnq/nefLetFSEV+dqBQzbNcG9ZRQrPYuWggEhlrcBT0tmQ3hgf/xe/PgmWUMBD7tAXrTAjcMkkdQAVYzXdi6pvTC2MwEGFNFBw/kxtjBL2pTKcXI9vjVQ8AaRoKszDv6WJtTFoPWTDiKr5P9RiY/Sxk9Hex0iA=
